### ISSUE TITLE
Bash / ZSH autocompletion functions

### ISSUE THREAD

**Issue by ajacksified** [lunarmodules/busted#241]
- [ ] bash
- [x] zsh

**Comment by o-lim** [comment]
I figured out a way to install the autocompletion functions with luarocks.  Basically, I added a Makefile, to do the install, and changed the build back-end to `make`.  I could use some help with testing it on different systems, and I didn't know how to disable the install on Windows.

Give it a try at o-lim/busted@a0aa66e.

**Comment by o-lim** [comment]
Installing via LuaRocks is probably not a good idea.  Instead the auto-completion functions should be installed as part of a Debian, Homebrew, and Red Hat packages, since the destination directories are platform specific.  This should probably be part of issues #239, and #240.  Might want to have a Red Hat package as well.  You could even have separate packages to install the auto-completion functions.

**Comment by alerque** [comment]
I agree, installing shell completions via `luarocks` is not a good idea. This should be left to distro packagers that install via system tooling and not directly. Even though it is technically possible there are too many ways for it to go wrong and cause trouble rather than benefit.

Since the completions files do exist in the distribution I'm closing this issue as no further action seems required.
